Messages:
  ErrorMessages:
    "PlayerOnly": "&eDer Befehl ist nur für Spieler!"
    "NEArgs": "&eNicht genug Argumente!"
    "LangNoExist": "&eEs gibt keine Sprache mit so einem Namen."
    "helpMessage": "&eBenutze /setlang /sl or /stl"
  SuccessMessages:
    "LangSet": "&6Sprache erfolgreich gesetzt"
  Revivevals:
    "PlayerRevived": "&6%player% wurde wiederbelebt ;)"
    "YouRevived": "&6%player% Du wurdest wiederbelebt ;)"
    "Alive": "&6%player% Ist am leben"
    "OnlyOnline": "&eDu bist der einzige online"
