name: Revivable
version: '${project.version}'
main: revivable.Main
api-version: 1.19
commands:
  revive:
    description: Revives the selected Player.
    usage: /revive
    aliases: [rev, r]
    permission-message: You are not allowed to revive.
  reviveall:
    description: Revives the all Player.
    usage: /reviveall
    aliases: [revall, rall]
    permission-message: You are not allowed to revive.
  banrevive:
    description: Bans the player from being able to revive anyhow.
    usage: /revive ban
    aliases: [brev, br]
