name: RevivePlugin
version: '${project.version}'
main: reviveplugin.reviveplugin.Main
api-version: 1.19
commands:
  setLang:
    description: Changes the language
    usage: /setlang
    aliases: [stl, sl]
  revive:
    description: Revives the selected Player.
    usage: /revive
    aliases: [rev, r]
    permissions: allow.revive
    permission-message: You are not allowed to revive.
  reviveall:
    description: Revives the all Player.
    usage: /reviveall
    aliases: [revall, rall]
    permissions: allow.revive.all
    permission-message: You are not allowed to revive.
